---
title: "NBA Data"
output: html_document
date: '2022-06-13'
---

```{r setup, include=FALSE}
library(ggplot2)
library(caret)
library(tidyverse)
library(nbastatR)
library(sjmisc)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(highcharter))
```



```{r Salary, echo = FALSE}
library(dplyr)
df_salaries <-
hoopshype_salaries(
  teams = NULL,
  all_teams = TRUE,
  assume_player_opt_out = T,
  assume_team_doesnt_exercise = T,
  nest_data = F,
  return_message = TRUE
)
df_salaries = df_salaries[df_salaries['slugSeason'] == '2022-23',]
```

```{r 2017 Cohort}

df_drafts <-
drafts(draft_years = 2017, nest_data = FALSE, return_message = TRUE)
df_drafts

bref_stats <- bref_players_stats(
  seasons = 2020:2022,
  tables = c("advanced", "totals"),
  include_all_nba = F,
  only_totals = TRUE,
  nest_data = FALSE,
  assign_to_environment = TRUE,
  widen_data = TRUE,
  join_data = TRUE,
  return_message = TRUE
)


cohort2017 <- merge(df_drafts, bref_stats, by = "namePlayer")
cohort2017
```

```{r}

# Credit
cohort2017$credit <- (cohort2017$ptsTotals + cohort2017$trbTotals + cohort2017$astTotals + cohort2017$stlTotals + cohort2017$blkTotals) - (cohort2017$fgaTotals - cohort2017$fgmTotals) - (cohort2017$ftaTotals - cohort2017$ftmTotals) - cohort2017$tovTotals
# AV
cohort2017$AV <- (cohort2017$credit**(0.75))/21
cohort2017$Average_AV <- cohort2017$AV %>% group_by(cohort2017$namePlayer)



Average_AV_2017 <- group_by(cohort2017, namePlayer)
Average_AV_2017 <- summarise(Average_AV_2017, Average_AV = mean(AV, na.rm = TRUE), groupPosition)
Average_AV_2017 <- Average_AV_2017[!duplicated(Average_AV_2017$namePlayer), ]

```
```{r cash_per_min vs AV}
library(ggplot2)
ggplot(Average_AV_2017, aes(x=groupPosition, y=Average_AV)) + geom_point()
```
```{r}
library(ggplot2)
ggplot(full_tbl, aes(x=cash_per_min, y=AV, color = AVCategory)) + geom_point()
```

```{r gamesPlayed}
ggplot(data = full_tbl) +
  geom_histogram(mapping = aes(x = countGames), binwidth = 0.5)
```



```{r gamesPlayed by position}
ggplot(data = full_tbl, mapping = aes(x = AVCategory, y = minutes)) +
  geom_boxplot()
```



```{r cash_per_min vs AV}
games60_tbl <- filter(full_tbl, countGames >= 60)
ggplot(games60_tbl, aes(x=AVCategory, y=AV, color = AVCategory)) + geom_boxplot()

```




















```{r 2018 Cohort}
df_drafts <-
drafts(draft_years = 2016, nest_data = FALSE, return_message = TRUE)
df_drafts

adv_stats <- bref_players_stats(seasons = 2018:2022, tables = c("advanced", "per_game"))
adv_stats

cohort2017 <- merge(df_drafts, adv_stats, by = "namePlayer")
cohort2017



```

```{r B Ref stats}
bref_stats <- bref_players_stats(
  seasons = 2022,
  tables = c("advanced", "totals"),
  include_all_nba = F,
  only_totals = TRUE,
  nest_data = FALSE,
  assign_to_environment = TRUE,
  widen_data = TRUE,
  join_data = TRUE,
  return_message = TRUE
)
```



```{r Get Credit & AV }
# Credit
bref_stats$credit <- (bref_stats$ptsTotals + bref_stats$trbTotals + bref_stats$astTotals + bref_stats$stlTotals + bref_stats$blkTotals) - (bref_stats$fgaTotals - bref_stats$fgmTotals) - (bref_stats$ftaTotals - bref_stats$ftmTotals) - bref_stats$tovTotals
# AV
bref_stats$AV <- (bref_stats$credit**(0.75))/21
```



```{r Get $/MIN}
full_tbl <- merge(df_salaries, bref_stats, by = "namePlayer")
# Get MP & $/MIN
full_tbl$cash_per_min<- full_tbl$amountContract/full_tbl$minutesTotals


mean(na.omit(full_tbl$AV))
```


```{r}
Categories <- cut(full_tbl$AV, breaks = c(-Inf,6.104977,12.209954,Inf), labels = c("Low","Medium","High"))
Categories <- data.frame(Categories)
full_tbl$AVCategory <- Categories$Categories
full_tbl
```


```{r cash_per_min vs AV}
library(ggplot2)
ggplot(full_tbl, aes(x=cash_per_min, y=AV, color = groupPosition)) + geom_point()
```
```{r}
library(ggplot2)
ggplot(full_tbl, aes(x=cash_per_min, y=AV, color = AVCategory)) + geom_point()
```

```{r gamesPlayed}
ggplot(data = full_tbl) +
  geom_histogram(mapping = aes(x = countGames), binwidth = 0.5)
```



```{r gamesPlayed by position}
ggplot(data = full_tbl, mapping = aes(x = AVCategory, y = minutes)) +
  geom_boxplot()
```



```{r cash_per_min vs AV}
games60_tbl <- filter(full_tbl, countGames >= 60)
ggplot(games60_tbl, aes(x=AVCategory, y=AV, color = AVCategory)) + geom_boxplot()
```

```{r}

detect_outliers <- function(inp, na.rm=TRUE) {
  i.qnt <- quantile(inp, probs=c(.25, .75), na.rm=na.rm)
  i.max <- 1.5 * IQR(inp, na.rm=na.rm)
  otp <- inp
  otp[inp < (i.qnt[1] - i.max)] <- NA
  otp[inp > (i.qnt[2] + i.max)] <- NA
  inp[is.na(otp)]
}

sum(is.na(full_tbl$AVCatagory))


#lapply(select(general, -c(groupPosition, slugPosition, slugTeamsBREF)), detect_outliers)

full_tbl$slugTeamBREF <- as.factor(full_tbl$slugTeamBREF)
full_tbl$slugPosition <- as.factor(full_tbl$slugPosition)
full_tbl$groupPosition <- as.factor(full_tbl$groupPosition)

full_tbl <- select(full_tbl, -isFinalSeason, -yearSeason, -isHOFPlayer, -nameTeam, -slugSeason.y, -isSeasonCurrent, -isPlayerOption, -countTeamsPlayerSeason, -isTeamOption, -slugSeason.x, -urlPlayerBREF, -urlPlayerThumbnail, -urlPlayerHeadshot, -urlPlayerPhoto, -urlPlayerActionPhoto, -urlHoopsHypePlayer, -urlTeamSalaryHoopsHype, -urlPlayerStats, -slugPlayerSeason, -slugPlayerBREF, -slugTeamsBREF, -idPlayerNBA)
str(full_tbl)

sum(is.na(full_tbl$amountContract))
```
```{r}
split1<- sample(c(rep(0, 0.7 * nrow(full_tbl)), rep(1, 0.3 * nrow(full_tbl))))
split1
TrainData <- full_tbl[split1 == 0, ]
TrainData
TestData <- full_tbl[split1== 1, ]
TestData
```
```{r}

stpModel=step(lm(data=TrainData, AVCategory~.), direction = "backward")
stpSummary <- summary(stpModel)
stpSummary 
```
```{r}
#model<- glm(amountContract ~ groupPosition + 
#    agePlayer+ countGames + minutes + ratioPER + 
##    pctTrueShooting + pct3PRate + pctFTRate + pctORB + pctDRB + 
#    pctTRB + pctAST + pctSTL + pctBLK + pctTOV + pctUSG + ratioOWS + 
#    ratioDWS + ratioWS + ratioWSPer48 + ratioOBPM + ratioDBPM + 
#    ratioBPM + ratioVORP + countGamesStarted + pctFG + pctFG3 + 
#    pctFG2 + pctEFG + pctFT + fgmTotals + fgaTotals + 
#    fg3mTotals + fg3aTotals + ftmTotals + 
#    ftaTotals + orbTotals + drbTotals + astTotals + 
#    stlTotals + blkTotals + tovTotals + pfTotals + cash_per_min + 
#    AVCategory, data = TrainData)
#summary(model)


model2 <- glm(AVCategory~. data = TrainData, family = 'binomial')  
summary(model2)

p1 <- predict(model2, TrainData, type = 'response')
head(p1)

pre1<-ifelse(p1 > 0.5, 1, 0)
table<-table(Prediction = pre1, 
             Actual = TrainData$AVCategory) 
table
```
```{r}
PredData <- select(TestData, c(groupPosition , agePlayer , countGames , 
    minutes , ratioPER , pctTrueShooting , pct3PRate , pctFTRate , 
    pctORB , pctDRB , pctTRB , pctAST , pctSTL , pctBLK , pctTOV , 
    pctUSG , ratioOWS , ratioDWS , ratioWS , ratioWSPer48 , ratioOBPM , 
    ratioDBPM , ratioBPM , ratioVORP , countGamesStarted , pctFG , 
    pctFG3 , pctFG2 , pctEFG , pctFT , fgmTotals , fgaTotals , 
    fg3mTotals , fg3aTotals , ftmTotals , ftaTotals , orbTotals , 
    drbTotals , astTotals , stlTotals , blkTotals , 
    tovTotals , pfTotals ,cash_per_min , AVCategory))

head(PredData)
```
```{r}
pred_sl <- predict(model2, PredData)
pred_sl

pred_sl <- predict(model, PredData)
pred_sl

TestData <- cbind(TestData, pred_sl)
TestData <- mutate(TestData, Accuracy = (1-(abs(amountContract-na.omit(pred_sl))/amountContract))*100)
TestData

summary(pred_sl)
```
```{r}
avgacc <- mean(na.omit(TestData$Accuracy))
avgacc
TestData$Accuracy
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
