---
title: "nbastatR"
output: html_document
date: '2022-06-13'
---

```{r setup, include=FALSE}
library(ggplot2)
library(caret)
library(tidyverse)
library(nbastatR)
suppressPackageStartupMessages(library(tidyverse))
# suppressPackageStartupMessages(library(highcharter))
```



```{r cohort creation function}
get_cohort <- function(cohort_year, season_range){
  
  # Get draft data
  df_drafts <- drafts(draft_years = cohort_year, nest_data = FALSE, return_message = FALSE)
  
  # Get bref data
  bref_stats <- bref_players_stats(
    seasons = season_range,
    tables = c("advanced", "totals"),
    include_all_nba = F,
    only_totals = TRUE,
    nest_data = FALSE,
    assign_to_environment = TRUE,
    widen_data = TRUE,
    join_data = TRUE,
    return_message = FALSE
  )
  
  # Merge draft and bref data
  cohort_tbl <- merge(df_drafts, bref_stats, by = "namePlayer")
  # Add column for cohort year
  cohort_tbl$year <- cohort_year

  # Credit
  cohort_tbl$credit <- (cohort_tbl$ptsTotals + cohort_tbl$trbTotals + cohort_tbl$astTotals + cohort_tbl$stlTotals + cohort_tbl$blkTotals) - (cohort_tbl$fgaTotals - cohort_tbl$fgmTotals) - (cohort_tbl$ftaTotals - cohort_tbl$ftmTotals) - cohort_tbl$tovTotals
  
  # AV
  cohort_tbl$AV <- (cohort_tbl$credit**(0.75))/21
  
  # Group by player
  Average_AV <- group_by(cohort_tbl, namePlayer)
  # Summarise AV mean, include groupPosition and year columns as-is
  Average_AV <- summarise(Average_AV, Average_AV = mean(AV, na.rm = TRUE), groupPosition, year, nameOrganizationFrom, typeOrganizationFrom)
  # Removing duplicate rows
  Average_AV <- Average_AV[!duplicated(Average_AV$namePlayer), ]
  
  
  Average_AV <- Average_AV %>% filter(typeOrganizationFrom == "College/University")
  
  # Return Average AV tibble
  return(Average_AV)
}

```



```{r Get Cohorts 2010 - 2017}
cohort2017 <- get_cohort(2017, 2020:2022)
cohort2016 <- get_cohort(2016, 2019:2021)
cohort2015 <- get_cohort(2015, 2018:2020)
cohort2014 <- get_cohort(2014, 2017:2019)
cohort2013 <- get_cohort(2013, 2016:2018)
cohort2012 <- get_cohort(2012, 2015:2017)
cohort2011 <- get_cohort(2011, 2014:2016)
cohort2010 <- get_cohort(2010, 2013:2015)
```

```{r all cohorts}
# Combine all cohorts
all_cohorts <- bind_rows(cohort2017, cohort2016, cohort2015, cohort2014, cohort2013, cohort2012, cohort2011, cohort2010)
```





```{r AV by position}

ggplot(all_cohorts, aes(x=groupPosition, y=Average_AV)) + geom_point()
```



```{r Get mean for all cohorts}
full_tbl <- merge(df_salaries, bref_stats, by = "namePlayer")

print(mean(na.omit(all_cohorts$Average_AV)))
print(mean(na.omit(all_cohorts$Average_AV))*2)

```


```{r Label AV values}
Categories <- cut(all_cohorts$Average_AV, breaks = c(-Inf,5.313925,10.62785,Inf), labels = c("Low","Medium","High"))
Categories <- data.frame(Categories)
all_cohorts$AVCategory <- Categories$Categories
all_cohorts
```


```{r all cohorts category count, fill by group position}
ggplot(all_cohorts, aes(x=AVCategory, fill=groupPosition)) + geom_bar()
```
```{r Get unique colleges from all cohort}

# distinct_schools <- unique(all_cohorts$nameOrganizationFrom)
# 
# distinct_schools <- as_tibble(distinct_schools) 
# distinct_schools <- rename(distinct_schools, Team = value)
# 
# distinct_schools

# test <- full_join(distinct_schools, school_id_tbl, by = "Team", keep = TRUE)
# write_excel_csv(test, "school_tbl_.csv")

```



```{r College data merge prep}
# Manually mapped unmatched schools and saved it to school_tbl.csv
school_id_tbl <- read_csv("school_tbl.csv")

# Join all cohorts with the school id tbl
full_tbl <- full_join(all_cohorts, school_id_tbl, by = "nameOrganizationFrom")

# Adjust namePlayer col for the college data merge
full_tbl <- full_tbl %>% mutate(namePlayer = toupper(namePlayer))
full_tbl <- full_tbl %>% mutate(namePlayer = str_replace_all(namePlayer, fixed(" "), "."))

full_tbl

```




```{r test ncca stat pull}
library(bigballR)

team = "Kentucky"
schedule <- get_team_schedule(season = "2016-17", team.name = team)

# Get play by play for all games played so far in season
play_by_play <- get_play_by_play(schedule$Game_ID)

# Generate all lineups and stats from the play by play
lineups <- get_player_stats(play_by_play_data = play_by_play, multi.games=TRUE)
lineups <- lineups %>% filter(Team == team)
lineups
```



